### ISSUE TITLE
Estimation in cross validation approach

### ISSUE THREAD

**Issue by AlbertoImg** [dgopstein/clust.bin.pair#1]
Hi @dgopstein,

Thanks for the package, it is really helpful and appreciated.
I wonder whether you have an idea how you would integrate these metrics when working with matched-pair clustered data and cross validation. For example there are statistics such as 5x2CV t test [Dietterich 1998] and 5x2CV [Alpaydin 1998] F test that account for the variance underestimation due to set overlapping in training and testing in cross-validation.
Thanks in advance
Best
Alberto

**Comment by dgopstein** [comment]
Hey @AlbertoImg,

Unfortunately, I'm not familiar with the world of cross validation, so can't really help, sorry! I hope you can figure out what you need elsewhere though. If you end up making local modifications to this package that you think might benefit others in the future, please feel free to propose them back as a pull request.

Thanks,
Dan
